style = "yas"  # base style

indent = 4
margin = 92

ignore =["docs"]
format_docstrings = true
always_for_in = false
indent_submodule = true
always_use_return = false
separate_kwargs_with_semicolon = false