name = "StellarOpacity"
uuid = "eeb08737-d0df-4e7c-8b49-e5a607c545fb"
authors = ["Pablo Marchant <pablo.marchant@kuleuven.be>"]
version = "0.1.0"

[deps]
StellarChem = "a84afe3b-952c-41e2-bc6a-6760f116ab93"
StellarConstants = "6f81b052-5a35-46da-9297-247d6ebafa96"
