name = "Jems"
uuid = "80e28b2b-5ac7-4db2-b78d-9e35bb8cec21"
authors = ["Pablo Marchant <pablo.marchant@kuleuven.be>", "Matthias Fabry <matthias.fabry@kuleuven.be>"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
